// <auto-generated />
using System;
using FinReportsandAnalitics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinReportsandAnalitics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230604071221_Initiale")]
    partial class Initiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinReportsandAnalitics.Models.BalanceRepot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBalanse")
                        .HasColumnType("datetime2");

                    b.Property<long>("_1100")
                        .HasColumnType("bigint");

                    b.Property<long>("_1110")
                        .HasColumnType("bigint");

                    b.Property<long>("_1120")
                        .HasColumnType("bigint");

                    b.Property<long>("_1130")
                        .HasColumnType("bigint");

                    b.Property<long>("_1140")
                        .HasColumnType("bigint");

                    b.Property<long>("_1150")
                        .HasColumnType("bigint");

                    b.Property<long>("_1160")
                        .HasColumnType("bigint");

                    b.Property<long>("_1170")
                        .HasColumnType("bigint");

                    b.Property<long>("_1180")
                        .HasColumnType("bigint");

                    b.Property<long>("_1190")
                        .HasColumnType("bigint");

                    b.Property<long>("_1200")
                        .HasColumnType("bigint");

                    b.Property<long>("_1210")
                        .HasColumnType("bigint");

                    b.Property<long>("_1220")
                        .HasColumnType("bigint");

                    b.Property<long>("_1230")
                        .HasColumnType("bigint");

                    b.Property<long>("_1240")
                        .HasColumnType("bigint");

                    b.Property<long>("_1250")
                        .HasColumnType("bigint");

                    b.Property<long>("_1260")
                        .HasColumnType("bigint");

                    b.Property<long>("_1300")
                        .HasColumnType("bigint");

                    b.Property<long>("_1310")
                        .HasColumnType("bigint");

                    b.Property<long>("_1320")
                        .HasColumnType("bigint");

                    b.Property<long>("_1340")
                        .HasColumnType("bigint");

                    b.Property<long>("_1350")
                        .HasColumnType("bigint");

                    b.Property<long>("_1360")
                        .HasColumnType("bigint");

                    b.Property<long>("_1370")
                        .HasColumnType("bigint");

                    b.Property<long>("_1400")
                        .HasColumnType("bigint");

                    b.Property<long>("_1410")
                        .HasColumnType("bigint");

                    b.Property<long>("_1420")
                        .HasColumnType("bigint");

                    b.Property<long>("_1430")
                        .HasColumnType("bigint");

                    b.Property<long>("_1450")
                        .HasColumnType("bigint");

                    b.Property<long>("_1500")
                        .HasColumnType("bigint");

                    b.Property<long>("_1510")
                        .HasColumnType("bigint");

                    b.Property<long>("_1520")
                        .HasColumnType("bigint");

                    b.Property<long>("_1530")
                        .HasColumnType("bigint");

                    b.Property<long>("_1540")
                        .HasColumnType("bigint");

                    b.Property<long>("_1550")
                        .HasColumnType("bigint");

                    b.Property<long>("_1600")
                        .HasColumnType("bigint");

                    b.Property<long>("_1700")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.ToTable("BalanceRepots");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.FinResultReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBalanse")
                        .HasColumnType("datetime2");

                    b.Property<long>("_2100")
                        .HasColumnType("bigint");

                    b.Property<long>("_2110")
                        .HasColumnType("bigint");

                    b.Property<long>("_2120")
                        .HasColumnType("bigint");

                    b.Property<long>("_2200")
                        .HasColumnType("bigint");

                    b.Property<long>("_2210")
                        .HasColumnType("bigint");

                    b.Property<long>("_2220")
                        .HasColumnType("bigint");

                    b.Property<long>("_2300")
                        .HasColumnType("bigint");

                    b.Property<long>("_2310")
                        .HasColumnType("bigint");

                    b.Property<long>("_2320")
                        .HasColumnType("bigint");

                    b.Property<long>("_2330")
                        .HasColumnType("bigint");

                    b.Property<long>("_2340")
                        .HasColumnType("bigint");

                    b.Property<long>("_2350")
                        .HasColumnType("bigint");

                    b.Property<long>("_2400")
                        .HasColumnType("bigint");

                    b.Property<long>("_2410")
                        .HasColumnType("bigint");

                    b.Property<long>("_2411")
                        .HasColumnType("bigint");

                    b.Property<long>("_2412")
                        .HasColumnType("bigint");

                    b.Property<long>("_2460")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.ToTable("FinResultReports");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.GuidForReportLines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeOfRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GuidForReports");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.BalanceRepot", b =>
                {
                    b.HasOne("FinReportsandAnalitics.Models.Company", "Company")
                        .WithMany("balanceRepots")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.FinResultReport", b =>
                {
                    b.HasOne("FinReportsandAnalitics.Models.Company", "Company")
                        .WithMany("finResultReports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FinReportsandAnalitics.Models.Company", b =>
                {
                    b.Navigation("balanceRepots");

                    b.Navigation("finResultReports");
                });
#pragma warning restore 612, 618
        }
    }
}
